unique: unique.cpp
	g++ unique.cpp -o unique

priority_queue: priority_queue.cpp
	g++ priority_queue.cpp -o priority_queue

text_generation: text_generation.cpp
	g++ text_generation.cpp -o text_generation
	