product: product.cpp
	g++ product.cpp -o product

divisible_by: divisible_by.cpp
	g++ divisible_by.cpp -o divisible_by

collatz: collatz.cpp
	g++ collatz.cpp -o collatz

sqrt: sqrt.cpp
	g++ sqrt.cpp -o sqrt

calculator: calculator.cpp
	g++ calculator.cpp -o calculator

reformat: reformat.cpp
	g++ reformat.cpp -o reformat

longest_line: longest_line.cpp
	g++ longest_line.cpp -o longest_line
